import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useToggle } from 'react-use'
import { Button } from 'antd'
import InviteModal from '../components/InviteModal'

const Home: NextPage = () => {
  const [on, toggle] = useToggle(false)
  return (
    <>
      <div style={{ minHeight: '100vh' }}>
        <Head>
          <title>Welcome to Broccoli & Co.</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.container}>
        <nav>
          <div className="max-w-6xl mx-auto px-4">
            <div className="flex justify-between">
              <div className="flex space-x-4">
                <div>
                  <a href="#" className="flex items-center py-5 px-2 text-gray-700">
                    <span className="font-bold">Broccoli & Co</span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </nav>
        <main className={styles.main}>
          <h1 className={styles.title}>A better way to enjoy every day.</h1>
          <p className={styles.description}>Be the first to know when we launch</p>
          <Button onClick={() => toggle(true)} type="primary"><span className="mx-4 py-auto">Request an invite</span></Button>

        </main>
        <footer className= "py-8 mx-auto">
          <div className="flex justify-center">
            <div>Made with ❤️ in Melbourne. </div>
          </div>
          <div className="flex justify-center">
            <div>© Broccoli & Co. 2021. All rights reserved.</div>
          </div>
          </footer>
        </div>
        <InviteModal visible={on} onCancel={() => toggle(false)} />
      </div>
    </>
  )
}

export default Home
