import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useToggle } from 'react-use'
import InviteModal from '../components/InviteModal'
import { Button } from 'antd'
import { mockData } from './api/emails'

const Home: NextPage = () => {
  const [on, toggle] = useToggle(false)
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Welcome to  Broccoli & Co.</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            A better way to enjoy every day.
          </h1>



          <p className={styles.description}>
            Be the first to know when we launch
          </p>

          <div className={styles.grid}>
            <button className={styles.card} onClick={() => toggle(true)}>
              <h2>Request an invite</h2>
            </button>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
      <InviteModal visible={on} onCancel={() => toggle(false)} />
    </>
  )
}

export default Home
